version: '3.8'

services:
  backend:
    build:
      context: ./back-end/
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end/
    ports:
      - "3000:3000"

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge